COPY public._prisma_migrations (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) FROM stdin;
COPY public.access_grants (id, "userId", "courseId", "startAt", "endAt", "isActive", "createdAt", "updatedAt", "orderId") FROM stdin;
COPY public.analytics_events (id, "userId", "eventType", "eventData", metadata, "ipAddress", "userAgent", "createdAt") FROM stdin;
COPY public.answers (id, "userId", "questionId", content, "isAccepted", "createdAt", "updatedAt") FROM stdin;
COPY public.coupons (id, code, type, value, "maxUses", "usedCount", "isActive", "validFrom", "validUntil", "createdAt", "updatedAt") FROM stdin;
COPY public.course_views (id, "courseId", "userId", "viewType", duration, progress, "createdAt") FROM stdin;
COPY public.courses (id, title, slug, description, thumbnail, price, currency, duration, level, language, "instructorId", "isPublished", "metaTitle", "metaDescription", keywords, "createdAt", "updatedAt") FROM stdin;
COPY public.device_enroll_requests (id, "userId", "installId", platform, model, ip, "geoCountry", "requestId", status, "createdAt", "expiresAt") FROM stdin;
COPY public.lesson_progress (id, "userId", "lessonId", progress, duration, completed, "lastPosition", "createdAt", "updatedAt", "completedAt") FROM stdin;
COPY public.lessons (id, title, description, "videoUrl", duration, "order", "sectionId", "isPublished", "videoKey", thumbnail, subtitles, "createdAt", "updatedAt", "isFree", resources, "videoType", "pdfKey", "pdfUrl", "contentType", "pdfFileName", "pdfPages", "pdfSize") FROM stdin;
COPY public.message_attachments (id, "messageId", "fileName", "fileUrl", "fileType", "fileSize", "createdAt") FROM stdin;
COPY public.message_replies (id, "messageId", "userId", content, "isAdmin", "createdAt", "isRead") FROM stdin;
COPY public.messages (id, "userId", "adminId", subject, content, "messageType", status, "isRead", "createdAt", "updatedAt") FROM stdin;
COPY public.navigation (id, name, location, items, "isActive", "createdAt", "updatedAt") FROM stdin;
COPY public.notes (id, "userId", "lessonId", content, "timestamp", "isPublic", "createdAt", "updatedAt") FROM stdin;
COPY public.orders (id, "userId", currency, status, amount, "courseId", "expiresAt", "invoiceNumber", metadata, "paymentIntentId", "purchasedAt", "paymentMethod", "billingInfo", "orderNumber") FROM stdin;
COPY public.pages (id, title, slug, content, "metaTitle", "metaDescription", "isPublished", "publishedAt", "createdAt", "updatedAt") FROM stdin;
COPY public.questions (id, "userId", "lessonId", title, content, "isPinned", "isAccepted", "acceptedAnswerId", "createdAt", "updatedAt", "courseId") FROM stdin;
COPY public.sections (id, title, description, "order", "courseId", "isPublished", "createdAt", "updatedAt", duration, "totalLessons") FROM stdin;
COPY public.site_settings (id, key, value) FROM stdin;
COPY public.user_devices (id, "userId", "installId", "publicKey", platform, model, "userAgent", "firstIp", "lastIp", "lastSeenAt", "isTrusted", "isActive", "approvedAt", "deviceName", "osVersion", "appVersion", "createdAt", "updatedAt") FROM stdin;
COPY public.user_sessions (id, "userId", "sessionId", "isActive", "startedAt", "lastActivity", "ipAddress", "userAgent", "deviceId") FROM stdin;
COPY public.users (id, email, "firstName", "lastName", password, role, "isActive", "emailVerified", "emailVerifiedAt", avatar, phone, bio, website, "createdAt", "updatedAt") FROM stdin;
COPY public.video_analytics (id, "videoId", "userId", "lessonId", action, "timestamp", duration, "createdAt") FROM stdin;
COPY public.videos (id, title, description, url, thumbnail, duration, "lessonId", "isActive", "createdAt", "updatedAt") FROM stdin;
